function h = build_interface(self)

  % check if window is already opened
  h = [ findall(0, 'Tag','StarGo_window') findall(0, 'Tag','StarGo_GUI') ];
  if ~isempty(h)
    set(0,'CurrentFigure', h); % make it active
  else  
    % else create
    h = openfig('stargo.fig');
    
    % uicontrols
    Callbacks = { ...
    'stargo_status' @(src,evnt)getstatus(self,'full'); ...
    'stargo_s'      @(src,evnt)move(self, 's','pulse'); ...
    'stargo_n'      @(src,evnt)move(self, 'n','pulse'); ...
    'stargo_e'      @(src,evnt)move(self, 'e','pulse'); ...
    'stargo_w'      @(src,evnt)move(self, 'w','pulse'); ...
    'stargo_stop'   @(src,evnt)stop(self); ...
    'stargo_zoom'   @(src,evnt)zoom(self, get(gcbo, 'Value')); ...
    'stargo_ra'     @(src,evnt)goto(self, get(gcbo, 'String'), ''); ...
    'stargo_dec'    @(src,evnt)goto(self, '', get(gcbo, 'String')); ...
    'stargo_pulse'  @(src,evnt)pulse(self, get(gcbo, 'String')); ...
    };
    
    build_callbacks(self, h, Callbacks);
  end
  
  return
  
  % assign button callbacks to private functions
  Callbacks = {...
    'StarGo_RA',     @(src,evnt)goto(self, get(gcbo, 'String'), ''); ...
    'StarGo_DEC',    @(src,evnt)goto(self, '', get(gcbo, 'String')); ...
    'StarGo_zoom',   @(src,evnt)zoom(self, get(gcbo, 'Value')); ...
    'StarGo_N',      @(src,evnt)move(self, 'n'); ...
    'StarGo_S',      @(src,evnt)move(self, 's'); ...
    'StarGo_W',      @(src,evnt)move(self, 'w'); ...
    'StarGo_E',      @(src,evnt)move(self, 'e'); ...
    'StarGo_Stop',   @(src,evnt)stop(self); ...
    'StarGo_goto',       @(src,evnt)goto(self); ...
    'StarGo_STOP',       @(src,evnt)stop(self); ...
    'StarGo_sync',       @(src,evnt)align(self); ...
    'StarGo_zoom_in',    @(src,evnt)zoom(self,'in'); ...
    'StarGo_zoom_out',   @(src,evnt)zoom(self,'out'); ...
    'StarGo_zoom_guide',   @(src,evnt)zoom(self,1); ...
    'StarGo_zoom_center',  @(src,evnt)zoom(self,2); ...
    'StarGo_zoom_find',    @(src,evnt)zoom(self,3); ...
    'StarGo_zoom_max',     @(src,evnt)zoom(self,4); ...
    'Home_set',            @(src,evnt)home(self,'set'); ...
    'Home_goto',           @(src,evnt)home(self); ...
    'Track_sidereal',      @(src,evnt)write(self,'set_tracking_sidereal'); ...
    'Track_sun',           @(src,evnt)write(self,'set_tracking_solar'); ...
    'Track_moon',          @(src,evnt)write(self,'set_tracking_lunar'); ...
    'Track_none',          @(src,evnt)write(self,'set_tracking_none'); ...
    'Park_set',            @(src,evnt)park(self,'set'); ...
    'Park_goto',           @(src,evnt)park(self,'goto'); ...
    'Park_unpark',         @(src,evnt)unpark(self); ...
    'StarGo_reset',        @(src,evnt)start(self); ...
    'StarGo_settings',     @(src,evnt)settings(self); ...
    'View_Update',         @(src,evnt)getstatus(self,'full'); ...
    'View_SkyMap',         @(src,evnt)web(self); ...
    'View_Location',       ''; ...
    'View_Help',           @(src,evnt)help(self); ...
    'View_About',          @(src,evnt)about(self) };
    
  % menus
  Callbacks = { ...
    'menu_view'
    'menu_stargo'
    'menu_file'
    'view_about'
    'view_help'
    'view_location'
    'view_skymap'
    'view_auto_update'
    'view_update'
    'stargo_settings'
    'stargo_reset'
    'track'
    'stargo_park'
    'stargo_home'
    'stargo_zoom'
    'stargo_sync'
    'stargo_stop'
    'stargo_goto'
    'file_close'
    'file_print'
    'file_saveas'
    'file_save'
    'track_none'
    'track_moon'
    'track_sun'
    'track_sidereal'
    'park_unpark'
    'park_goto'
    'park_set'
    'home_goto'
    'home_set'
    'stargo_zoom_max'
    'stargo_zoom_find'
    'stargo_zoom_center'
    'stargo_zoom_guide'
    'stargo_zoom_out'
    'stargo_zoom_in' };
    
% ------------------------------------------------------------------------------

function build_callbacks(self, h, Callbacks)
  for index=1:size(Callbacks,1)
    obj = findobj(h, 'Tag', Callbacks{index,1});
    if ~isscalar(obj)
      disp([ mfilename ': Invalid Tag ' Callbacks{index,1} ' in GUI' ])
    else
      set(obj, 'Callback', Callbacks{index,2})
    end
  end

